# 2024-08-20 TIL

## 백준 오답 노트

### 2908번 상수 문제   
### 문제의 코드
```python
A, B = input().split()
reA = int(A.reverse())
reB = int(B.reverse())

print = max(reA, reB)
```
### 코드의 작동 방식   
-입력: 입력을 받아 공백을 기준으로 두 부분으로 나눈 뒤, A와 B에 각각 문자열 형태로 저장한다.        
-reverse(): 배열 요소를 역순으로 정렬하는 함수이다.      
-출력: print 문을 통해 reA와 reB 중 큰 값을 출력한다.       

-오류의 원인: 정수값에는 reverse() 메소드가 없습니다, print문을 잘못 작성하였습니다.     


### 수정된 코드
```python
A, B = map(int, input().split())
reA = int(str(A)[::-1])
reB = int(str(B)[::-1])

print(max(reA, reB))
```
### 수정 사항

-map(int, input().split())을 사용해 문자열을 입력 받고, 공백을 기준으로 나눈 뒤, 문자열을 정수로 변환하였습니다. 그 값들을 A, B에 할당합니다.          
-정수형이였던 A와 B를 다시 문자열로 변환 후 [::-1]를 사용해 문자열을 뒤집어 다시 정수로 변환합니다.           
-뒤집혔던 A와 B 값을 비교해 큰 값을 출력합니다

### 수정된 코드의 출력   

```
734 893
437
```
다음과 같은 출력이 나옵니다.   

*****

### 11718번 그대로 출력하기 문제
### 문제의 코드
```python
while True:
	try:
		A = input().strip()
		print(A)
	except:
		break
```
### 코드의 작동 방식
-반복문: while True:로 무한 루프를 실행합니다, 이 루프는 명시적으로 중단 되기 전까지는 계속 반복됩니다.            
-입력: 사용자로부터 한 줄의 입력을 받고, 입력된 문자열의 앞뒤 공백을 제거합니다.       
-출력: 입력받은 문자열 A를 그대로 출력합니다.            
-예외: except: try 블록에서 오류가 발생하면 이 블록이 실행되고 break:문으로 while 루프를 종료합니다.                   

### 오류의 원인
입력이 비어있는지 확인한느 코드를 생성하지 않았기 때문에 공백만 입력하거나 아무것도 입력하지 않고 엔터만 쳐도 계속 실행되는 코드이다.    
런타임 에러 발생             

### 수정한 코드
```python
import sys
while True:
	A = sys.stdin.readline().strip()
	print(A)
	if not A:
		break
```

### 코드의 작동 방식
-생성: python의 sys 모듈을 가져옵니다.              
-반복문: while True:로 무한 루프를 실행합니다, 이 루프는 명시적으로 중단 되기 전까지는 계속 반복됩니다.     
-입력: sys.stdin.readline()을 통해 좀 더 효율적으로 입력값을 읽고 앞뒤 공백을 제거합니다.      
-출력: 입력받은 문자열 A를 그대로 출력합니다.
-확인: if not A:로 A가 빈 문자열인지 확인하고 빈 문자열일 경우 while 루프를 종료합니다.      

### 수정된 코드의 출력   
```
Hello
Hello
Baekjoon
Baekjoon
Online Judge
Online Judge
```
다음과 같은 출력이 나옵니다.

*****

### 5622번 다이얼 문제
### 문제의 코드
```python
A = int(input())
for i in range(A + 1):
    i += A
print(i)
```
### 코드의 작동 방식
-입력: A에 사용자가 입력한 정수 값을 저장합니다.   
-반복문: range(A + 1)은 0부터 A까지의 숫자(총 A + 1개)를 생성합니다. 이 반복문은 각 반복마다 시퀀스의 다음 값을 i에 대입합니다.    
-i 변경: i += A는 i의 현재 값에 A를 더한 값을 i에 다시 저장합니다.       
-i 초기화: 그러나 for 루프는 다음 반복에서 i를 시퀀스의 다음 값으로 덮어씁니다. 따라서, i의 변경은 다음 반복에 영향을 주지 않습니다.         
출력: 반복문이 끝난 후 마지막 i 값을 출력합니다. 이 값은 range(A + 1)의 마지막 값에 A를 더한 값입니다.           

### 오류의 원인
코드가 기대와 다르게 작동한 이유는 for 루프 내부에서 i를 변경하더라도 이 변경이 다음 반복에 영향을 주지 않기 때문입니다.    
각 반복은 range 시퀀스의 다음 값으로 i를 초기화합니다.     
따라서 i가 반복 내에서 변경되어도 다음 반복에서 그 변경된 값을 사용할 수 없습니다.      

### 예시
A = 3일 때   
반복 1: i = 0, i += 3 → i = 3   
반복 2: i = 1, i += 3 → i = 4   
반복 3: i = 2, i += 3 → i = 5   
반복 4: i = 3, i += 3 → i = 6   
반복문이 끝나면 i는 6이 되어 출력됩니다.   


### 수정한 코드
```python
A = int(input())
result = 0

for i in range(A + 1):
	result += i
print(result)
```

### 코드의 작동 방식
-입력: A에 사용자가 입력한 정수 값을 저장합니다.   
-입력: result 변수를 0의 값으로 생성합니다.   
-반복문: range(A + 1)은 0부터 A까지의 숫자(총 A + 1개)를 생성합니다. 이 반복문은 각 반복마다 시퀀스의 다음 값을 i에 대입합니다.   
-result 변경: result += i는 result의 현재 값 0에 i를 더한 값을 result에 다시 저장합니다.   
-출력: 반복문이 끝난 후 마지막 result 값을 출력합니다. 이 값은 i의 시퀀스 값을 result에 더한 값입니다.   

### 수정된 코드의 출력   
'A = 3'를 입력하면 
```
6
```
다음과 같은 출력이 나옵니다.
