## 2024-08-14 회고
### 회고 목표: 실습 코드 오류 해결

실습 코드를 똑같이 실행해도 계속 오류가 발생했다.

오류 내용은 다음과 같다.
#### ImportError: cannot import name 'RegisterView' from 'users.views'

1번 오류에 대해서 해결 방법은 다음과 같다.

#### 1. RegisterView의 정의 위치 확인
views.py 파일 내에 RegisterView가 정확히 정의되어 있는지 확인한다.

이에 대해 내가 작성한 코드에서는 별다른 문제 없이 잘 정의 되어 있음을 확인하였다.

#### 2. 순환 참조 문제
순환 참조는 views.py 와 urls.py가 서로 참조하려고 할 때 발생하는 문제이다.

예를 들어 views.py에서 urls.py를 임포트하고 동시에 urls.py에서 views.py를 임포트하려 하면 순환 참조 문제가 발생한다.

하지만 내가 작성한 코드에서는 서로 참조하려는 코드가 아니기에 해당사항이 아니다.

#### 3. 모듈 경로 문제
만약 users라는 이름의 패키지가 있고 그 안에 views.py와 urls.py가 포함되어 있다면 상대경로를 올바르게 지정해야 한다.

마찬가지로 내가 작성한 코드에서는 모듈 경로는 문제가 발견되지 않았다.

하지만 from users.views import RegisterView로 수정하여 절대 경로로 임포트를 시도하였고 오류는 똑같이 발생하였다.

그 밖에도 여러 방법을 활용해봤지만 여전히 오류 문제가 발생하였다.

따라서 나는 어느 부분에서 오류가 나는 지 더 정확히 알기 위해 디버깅 메시지를 추가하였다.

```python
# users/views.py
print("Importing RegisterView...")
from users.views import RegisterView
print("RegisterView imported successfully!")
```
이 코드를 추가하고 실행해보니

**"Importing RegisterView..."**

이 문장만 출력되고 동일한 오류가 발생했다.

이를 통해 알 수 있는 사실은 views.py 파일이 제대로 로드되지 않거나, 그 과정에서 문제가 발생했다는 것이다.

따라서 추가로 할 수 있는 해결 방법으로는

#### views.py내부에서의 오류 확인
viwes.py 파일 내부에서 RegisterView를 정의하기 전, serializers.py 파일에서 정의된 RegisterSerializer를 가져오는 과정에서 문제가 생길 수 있으므로 serializers.py이 제대로 동작하는지 확인한다.

하지만 여전히 코드 내용에는 문제가 발견되지 않았고 추가로 나는 다른 오류 메시지를 확인할 수 있었다.

#### django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
이 오류 메시지에 대해 찾아보니 Django 프로젝트가 설정을 제대로 로드하지 못했을 때 발생하는 django.core.exceptions.ImproperlyConfigured 예외라고 한다.

이 메시지는 Django가 설정을 찾지 못하고 있다는 것을 의미한다고 한다. 주로 다음과 같은 두 가지 문제로 인해 발생할 수 있다.

- DJANGO_SETTINGS_MODULE 환경 변수 미설정: Django는 설정을 찾기 위해 DJANGO_SETTINGS_MODULE이라는 환경 변수를 사용한다. 이 환경 변수에 설정 모듈의 경로를 지정해야 한다.
- Django 설정을 직접 구성하지 않음: settings.configure()를 호출하여 설정을 수동으로 구성해야 할 경우도 있다.

이 오류를 해결하기 위해서는 Django 설정 모듈이 제대로 구성되었는지 확인하고, DJANGO_SETTINGS_MODULE 환경 변수를 올바르게 설정해야 한다.

또한, manage.py와 wsgi.py 파일에서 설정이 올바르게 지정되었는지 확인한다.

하지만 아무리 해결방안을 시도해도 똑같이 오류가 나서 결국 프로젝트를 완전히 삭제하고 처음부터 다시 코드를 실행해보니 오류없이 진행됐다.
(하지만 몇몇 기능들은 아직 안되는 것 같다.. python manage.py runserver를 실행했을 때 오류메시지가 안 뜨는 것에 의의를..)
